production:
  adapter: mysql2
  database: ccsm_production
  pool: 5
  host: localhost
  reconnect: false
  username: root
  password: "root"
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock
development:
  adapter: mysql2
  database: ccsm_development
  pool: 5
  host: localhost
  reconnect: false
  username: root
  password: "root"
  encoding: utf8
#  socket: /var/lib/mysql/mysql.sock

